version: '3.1'
name: ''
service:
  app:
    container_name: 
    image:
    restart: always
    environment:

    ports:
      
    depends_on:
      
  db:
    container_name: 
    image:
    restart: always
    volumes:
      - mongo:/data/db
volumes:
mongo: