version: '3.1'
services:
  wordpress:
    container_name: wp_server
    image: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: monomono
      WORDPRESS_DB_NAME: wp_db
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
  db:
    container_name: mysql_server
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: wp_db
      MARIADB_USER: user
      MARIADB_PASSWORD: monomono
      MARIADB_ROOT_PASSWORD: monomono
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin_server
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: monomono
    ports:
      - 8080:80
    depends_on:
      - db