version: '3.1'
services:
  wordpress:
    container_name: wp_server
    image: wordpress:${WP_VERSION}
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${USER}
      WORDPRESS_DB_PASSWORD: ${PASSWORD}
      WORDPRESS_DB_NAME: ${DATABASE_NAME}
    ports:
      - ${DDBB_PORT}:80
    volumes:
      - ./wordpress:/var/www/html
  db:
    container_name: mysql_server
    image: mariadb:${MARIADB_VERSION}
    restart: always
    environment:
      MARIADB_DATABASE: ${DATABASE_NAME}
      MARIADB_USER: ${USER}
      MARIADB_PASSWORD: ${PASSWORD}
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin_server
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - ${PHPMYADMIN_PORT}:80
    depends_on:
      - db